=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/ObjectType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by XMLSPY 2006 Professional Ed., Installed for 5 users (ABB Oy) -->
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Markku Hamarila/RSC (ABB OY Substation Automation) -->
<!--W3C Schema generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Access" type="xs:string"/>
	<xs:element name="AttributeName" type="xs:string"/>
	<xs:element name="HelpKey" type="xs:string"/>
	<xs:element name="CaptionID" type="xs:string"/>
	<xs:element name="ConfigurationProperties" type="xs:string"/>
	<xs:element name="DataType" type="xs:string"/>
	<xs:element name="DescID" type="xs:string"/>
	<xs:complexType name="EnumType">
		<xs:attribute name="textID" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ExportType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="ConfigurationProperties" minOccurs="0"/>
			<xs:element name="List" type="ListType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="exportType" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ListType">
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="properties" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Max" type="xs:integer"/>
	<xs:element name="Min" type="xs:integer"/>
	<xs:element name="ObjectTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ObjectType" type="tObjectType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ObjectType" type="tObjectType"/>
	<xs:complexType name="tObjectType">
		<xs:sequence>
			<xs:element name="Parameters" type="ParametersType" maxOccurs="unbounded"/>
			<xs:element name="Properties" type="PropertiesType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ParameterType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="List" type="ListType" maxOccurs="unbounded"/>
			<xs:element name="Structure" type="StructureType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ParametersType">
		<xs:choice>
			<xs:element name="Parameter" type="ParameterType" maxOccurs="unbounded"/>
			<xs:element name="Export" type="ExportType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PrivateType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PropertiesType">
		<xs:sequence>
			<xs:element name="Property" type="PropertyType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PropertyType">
		<xs:sequence>
			<xs:element ref="Value"/>
			<xs:element ref="DescID"/>
			<xs:element ref="CaptionID"/>
			<xs:element name="Values" type="ValuesType"/>
			<xs:element ref="DataType"/>
			<xs:element ref="HelpKey"/>
			<xs:element ref="Access"/>
			<xs:element ref="AttributeName" minOccurs="0"/>
			<xs:element name="Private" type="PrivateType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="category" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Value" type="xs:string"/>
	<xs:complexType name="ValuesType">
		<xs:sequence>
			<xs:element name="Enum" type="EnumType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="Min" minOccurs="0"/>
			<xs:element ref="Max" minOccurs="0"/>
			<xs:element name="ListObjects" type="ListObjectType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="numerical"/>
					<xs:enumeration value="singleChoice"/>
					<xs:enumeration value="singleChoiceDynamic"/>
					<xs:enumeration value="singleChoiceEditable"/>
					<xs:enumeration value="multiChoice"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="password"/>
					<xs:enumeration value="boolean"/>
					<xs:enumeration value="SoftPLCOPCItemPath"/>					
					<xs:enumeration value="DocumentLibraryReference"/>		
					<xs:enumeration value="IPOrHostname" />
					<xs:enumeration value="IPOrHostnameWithPort" />								
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="AndConditionsType">
		<xs:sequence>
			<xs:element name="Condition" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="OrConditions" type="OrConditionsType" minOccurs="0"/>
			<xs:element name="AndConditions" type="AndConditionsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConditionType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Name"/>
			<xs:element ref="Values"/>
		</xs:choice>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="DataStructureObjectType"/>
					<xs:enumeration value="PCMObjectType"/>
					<xs:enumeration value="PropertyValue"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Name" type="xs:string"/>
	<xs:complexType name="OrConditionsType">
		<xs:sequence>
			<xs:element name="Condition" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="AndConditions" type="AndConditionsType" minOccurs="0"/>
			<xs:element name="OrConditions" type="OrConditionsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StructureType">
		<xs:choice>
			<xs:element name="Condition" type="ConditionType"/>
			<xs:element name="OrConditions" type="OrConditionsType"/>
			<xs:element name="AndConditions" type="AndConditionsType"/>
			<xs:element name="ChildObject" type="ChildObjectType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="COMMUNICATION"/>
					<xs:enumeration value="FUNCTIONAL"/>
					<xs:enumeration value="PCMSTRUCTURE"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Values" type="xs:string"/>
	<xs:complexType name="ChildObjectType">
		<xs:sequence>
			<xs:element name="ChildObject" type="ChildObjectType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SetPropertyValue" type="SetPropertyValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SetPropertyValueType">
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ListObjectType">
		<xs:attribute name="findMethod" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="ancestorDirectChild"/>
					<xs:enumeration value="ancestorSecondChild"/>
					<xs:enumeration value="ancestorPropertyValue"/>
					<xs:enumeration value="ancestorPropertyValueWithDefaults"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ancestorDsot" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="OPCServer"/>
					<xs:enumeration value="OPCClient"/>
					<xs:enumeration value="LN"/>
					<xs:enumeration value="GATEWAY"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="childObjectType" type="xs:string"/>
		<xs:attribute name="firstchildObjectType" type="xs:string"/>
		<xs:attribute name="secondchildObjectType" type="xs:string"/>
		<xs:attribute name="filterDsot" type="xs:string"/>
		<xs:attribute name="filterObjectType" type="xs:string"/>
		<xs:attribute name="propertyName" type="xs:string"/>
		<xs:attribute name="expectedDefaults" type="xs:string"/>
		<xs:attribute name="separators" type="xs:string"/>
		<xs:attribute name="selectorIndexes" type="xs:string"/>
		<xs:attribute name="idIndex" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/Stepwise Linear.xml
<?xml version="1.0" encoding="UTF-8"?>
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">StepwiseLinear</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Scales</Parameter>
		<Parameter name="Type">SCALE</Parameter>
		<Parameter name="IconFileName">Scale stepwiselinear.ico</Parameter>
		<Parameter name="Tools"/>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">True</Parameter>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">ScaleGroup</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="CDATA">BaseType, In1, Out1, In2, Out2, In3, Out3, In4, Out4, In5, Out5, In6, Out6, In7, Out7, In8, Out8, In9, Out9, In10, Out10</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="OPCObjectType" category="[030] Basic">
			<Value>Scale</Value>
			<DescID>OPCObjectTypeDesc</DescID>
			<CaptionID>OPCObjectType</CaptionID>
			<Values type="string">
	      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>OPCObjectType</AttributeName>
		</Property>
		<Property name="BaseType" category="Basic">
			<Value>StepwiseLinear</Value>
			<DescID>BaseTypeDesc</DescID>
			<CaptionID>BaseType</CaptionID>
			<Values type="singleChoice">
				<Enum textID="Step-wise linear scale" value="StepwiseLinear"/>
				<Enum textID="Look-up table scale" value="LookupTable"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHR</Access>
			<AttributeName/>
		</Property>
		<Property name="Item" category="Basic">
			<Value/>
			<DescID>ItemDesc</DescID>
			<CaptionID>Item</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName/>
		</Property>
		<Property name="In1" category="Basic">
			<Value>-</Value>
			<DescID>In1Desc</DescID>
			<CaptionID>In1</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out1" category="Basic">
			<Value>-</Value>
			<DescID>Out1Desc</DescID>
			<CaptionID>Out1</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In2" category="Basic">
			<Value>-</Value>
			<DescID>In2Desc</DescID>
			<CaptionID>In2</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out2" category="Basic">
			<Value>-</Value>
			<DescID>Out2Desc</DescID>
			<CaptionID>Out2</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In3" category="Basic">
			<Value>-</Value>
			<DescID>In3Desc</DescID>
			<CaptionID>In3</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out3" category="Basic">
			<Value>-</Value>
			<DescID>Out3Desc</DescID>
			<CaptionID>Out3</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In4" category="Basic">
			<Value>-</Value>
			<DescID>In4Desc</DescID>
			<CaptionID>In4</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out4" category="Basic">
			<Value>-</Value>
			<DescID>Out4Desc</DescID>
			<CaptionID>Out4</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In5" category="Basic">
			<Value>-</Value>
			<DescID>In5Desc</DescID>
			<CaptionID>In5</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out5" category="Basic">
			<Value>-</Value>
			<DescID>Out5Desc</DescID>
			<CaptionID>Out5</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In6" category="Basic">
			<Value>-</Value>
			<DescID>In6Desc</DescID>
			<CaptionID>In6</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out6" category="Basic">
			<Value>-</Value>
			<DescID>Out6Desc</DescID>
			<CaptionID>Out6</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In7" category="Basic">
			<Value>-</Value>
			<DescID>In7Desc</DescID>
			<CaptionID>In7</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out7" category="Basic">
			<Value>-</Value>
			<DescID>Out7Desc</DescID>
			<CaptionID>Out7</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In8" category="Basic">
			<Value>-</Value>
			<DescID>In8Desc</DescID>
			<CaptionID>In8</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out8" category="Basic">
			<Value>-</Value>
			<DescID>Out8Desc</DescID>
			<CaptionID>Out8</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In9" category="Basic">
			<Value>-</Value>
			<DescID>In9Desc</DescID>
			<CaptionID>In9</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out9" category="Basic">
			<Value>-</Value>
			<DescID>Out9Desc</DescID>
			<CaptionID>Out9</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="In10" category="Basic">
			<Value>-</Value>
			<DescID>In10Desc</DescID>
			<CaptionID>In10</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Out10" category="Basic">
			<Value>-</Value>
			<DescID>Out10Desc</DescID>
			<CaptionID>Out10</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
	</Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/Generic Rack.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Markku Hamarila/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">Rack</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">SPA</Parameter>
		<Parameter name="Type">RACK</Parameter>
		<Parameter name="IconFileName">Rack.ico</Parameter>
		<Parameter name="Tools"></Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">False</Parameter>
		<Parameter name="CanInherit">True</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="DataStructureObjectType">Subnetwork, LSG</Condition>
			</Structure>
		</Parameter>
	</Parameters>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/SNMP Subnetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">SNMP Subnetwork</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">SNMP</Parameter>
		<Parameter name="Type">SubNetwork</Parameter>
		<Parameter name="IconFileName">bus.ico</Parameter>
		<Parameter name="Tools"></Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">True</Parameter>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">SNMP OPC Server</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="CDATA">InUse, DeviceName</Export>
		<Export name="Addresses">IP</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="OPCObjectType" category="[010] Basic">
			<Value>ABB-SNMP</Value>
			<DescID>OPCObjectTypeDesc</DescID>
			<CaptionID>OPCObjectType</CaptionID>
			<Values type="string">
      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>OPCObjectType</AttributeName>
		</Property>
				<Property name="DeviceName" category="[020] Communication Port">
			<Value>ETH0</Value>
			<DescID>LAN port used by the IEC 61850 protocol</DescID>
			<CaptionID>Communication port</CaptionID>
			<Values type="singleChoice">
				<Enum textID="ETH0" value="ETH0"/>
				<Enum textID="ETH1" value="ETH1"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey>302</HelpKey>
			<Access>HHH</Access>
			<AttributeName>SD</AttributeName>
		</Property>
		<Property name="InUse" category="[010] Basic">
			<Value>1</Value>
			<DescID>Controls if the device communication is initially in use or not</DescID>
			<CaptionID>In Use</CaptionID>
			<Values type="singleChoice">
				<Enum value="1" textID="In Use"/>
				<Enum value="0" textID="Not In Use"/>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>InUse</AttributeName>
		</Property>
			<Property name="IP" category="[020] Communication Port">
			<Value>127.0.0.1</Value>
			<DescID>IP Address for communication channel. Dotted decimal or DNS name to be used</DescID>
			<CaptionID>IP Address</CaptionID>
			<Values type="string">
      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>IP</AttributeName>
		</Property>
	</Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/EventQueueFull.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
  <Parameters type="InterfaceDefinition">
    <Parameter name="ObjectType">EventQueueFull</Parameter>
    <Parameter name="Caption">objectTypeCaption</Parameter>
    <Parameter name="Description">objectTypeDesc</Parameter>
    <Parameter name="Group">Event Classes</Parameter>
    <Parameter name="Type">EVENT</Parameter>
    <Parameter name="IconFileName">ae.ico</Parameter>
    <Parameter name="Tools" />
    <Parameter name="DataServers" />
    <Parameter name="Verbs" />
    <Parameter name="Visible">True</Parameter>
    <Parameter name="CanInherit">False</Parameter>
    <Parameter name="ParentControlConditions">
      <Structure name="COMMUNICATION">
        <Condition type="PCMObjectType">EventGroupDCSEvents</Condition>
      </Structure>
    </Parameter>
  </Parameters>
  <Parameters type="SCLExport">
    <Export name="CDATA">
BaseType, 
EventBufferOverflowErrorMessage, 
SeverityOfEventBufferOverflowError, 
EventBufferOverflowErrorAckReq, 
EventBufferStateNormalMessage, 
EventBufferStateNormalAckReq, 
SendSimpleEvent
</Export>
  </Parameters>
  <Properties type="PropertyDefinitions">
    <Property name="OPCObjectType" category="[010] Basic">
      <Value>Event Class</Value>
      <DescID>OPCObjectTypeDesc</DescID>
      <CaptionID>OPCObjectType</CaptionID>
      <Values type="string">
      </Values>
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>HHR</Access>
      <AttributeName>OPCObjectType</AttributeName>
    </Property>
    <Property name="BaseType" category="[010] Basic">
      <Value>EventQueueFull</Value>
      <DescID>BaseTypeDesc</DescID>
      <CaptionID>BaseType</CaptionID>
      <Values type="singleChoice">
        <Enum textID="Discrete Indication" value="DiscInd" />
        <Enum textID="Limit Supervision" value="MVLevelBase" />
        <Enum textID="Trip Event" value="Trip" />
        <Enum textID="Advanced Discrete Indication" value="Discrete" />
        <Enum textID="Device Connection Status" value="DeviceConnectionStatus" />
        <Enum textID="Advanced Limit Supervision" value="Level" />
        <Enum textID="Quality Texts" value="Quality Texts" />
        <Enum textID="Event Queue Full Class" value="EventQueueFull" />
      </Values>
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>HHH</Access>
      <AttributeName />
    </Property>
    <Property name="EventBufferOverflowErrorMessage" category="[010] Basic">
      <Value>Event buffer overflow</Value>
      <DescID>EventBufferOverflowErrorMessageDesc</DescID>
      <CaptionID>EventBufferOverflowErrorMessage</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName />
    </Property>
    <Property name="EventBufferStateNormalMessage" category="[010] Basic">
      <Value>Event buffer normal</Value>
      <DescID>EventBufferStateNormalMessageDesc</DescID>
      <CaptionID>EventBufferStateNormalMessage</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName />
    </Property>
    <Property name="SeverityOfEventBufferOverflowError" category="[010] Basic">
      <Value>1000</Value>
      <DescID>SeverityOfEventBufferOverflowErrorDesc</DescID>
      <CaptionID>SeverityOfEventBufferOverflowError</CaptionID>
      <Values type="numerical">
        <Min>1</Min>
        <Max>1000</Max>
      </Values>
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName />
    </Property>
    <Property name="EventBufferStateNormalAckReq" category="[010] Basic">
      <Value>False</Value>
      <DescID>EventBufferStateNormalAckReqDesc</DescID>
      <CaptionID>EventBufferStateNormalAckReq</CaptionID>
      <Values type="boolean">
      </Values>
      <DataType>System.Boolean</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName />
    </Property>
    <Property name="EventBufferOverflowErrorAckReq" category="[010] Basic">
      <Value>False</Value>
      <DescID>EventBufferOverflowErrorAckReqDesc</DescID>
      <CaptionID>EventBufferOverflowErrorAckReq</CaptionID>
      <Values type="boolean">
      </Values>
      <DataType>System.Boolean</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName />
    </Property>
    <Property name="SendSimpleEvent" category="[010] Basic">
      <Value>False</Value>
      <DescID>SendSimpleEventDesc</DescID>
      <CaptionID>SendSimpleEvent</CaptionID>
      <Values type="boolean">
      </Values>
      <DataType>System.Boolean</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName />
    </Property>
  </Properties>
</ObjectType>
