=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/ObjectType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by XMLSPY 2006 Professional Ed., Installed for 5 users (ABB Oy) -->
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Markku Hamarila/RSC (ABB OY Substation Automation) -->
<!--W3C Schema generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Access" type="xs:string"/>
	<xs:element name="AttributeName" type="xs:string"/>
	<xs:element name="HelpKey" type="xs:string"/>
	<xs:element name="CaptionID" type="xs:string"/>
	<xs:element name="ConfigurationProperties" type="xs:string"/>
	<xs:element name="DataType" type="xs:string"/>
	<xs:element name="DescID" type="xs:string"/>
	<xs:complexType name="EnumType">
		<xs:attribute name="textID" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ExportType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="ConfigurationProperties" minOccurs="0"/>
			<xs:element name="List" type="ListType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="exportType" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ListType">
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="properties" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Max" type="xs:integer"/>
	<xs:element name="Min" type="xs:integer"/>
	<xs:element name="ObjectTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ObjectType" type="tObjectType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ObjectType" type="tObjectType"/>
	<xs:complexType name="tObjectType">
		<xs:sequence>
			<xs:element name="Parameters" type="ParametersType" maxOccurs="unbounded"/>
			<xs:element name="Properties" type="PropertiesType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ParameterType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="List" type="ListType" maxOccurs="unbounded"/>
			<xs:element name="Structure" type="StructureType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ParametersType">
		<xs:choice>
			<xs:element name="Parameter" type="ParameterType" maxOccurs="unbounded"/>
			<xs:element name="Export" type="ExportType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PrivateType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PropertiesType">
		<xs:sequence>
			<xs:element name="Property" type="PropertyType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PropertyType">
		<xs:sequence>
			<xs:element ref="Value"/>
			<xs:element ref="DescID"/>
			<xs:element ref="CaptionID"/>
			<xs:element name="Values" type="ValuesType"/>
			<xs:element ref="DataType"/>
			<xs:element ref="HelpKey"/>
			<xs:element ref="Access"/>
			<xs:element ref="AttributeName" minOccurs="0"/>
			<xs:element name="Private" type="PrivateType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="category" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Value" type="xs:string"/>
	<xs:complexType name="ValuesType">
		<xs:sequence>
			<xs:element name="Enum" type="EnumType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="Min" minOccurs="0"/>
			<xs:element ref="Max" minOccurs="0"/>
			<xs:element name="ListObjects" type="ListObjectType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="numerical"/>
					<xs:enumeration value="singleChoice"/>
					<xs:enumeration value="singleChoiceDynamic"/>
					<xs:enumeration value="singleChoiceEditable"/>
					<xs:enumeration value="multiChoice"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="password"/>
					<xs:enumeration value="boolean"/>
					<xs:enumeration value="SoftPLCOPCItemPath"/>					
					<xs:enumeration value="DocumentLibraryReference"/>		
					<xs:enumeration value="IPOrHostname" />
					<xs:enumeration value="IPOrHostnameWithPort" />								
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="AndConditionsType">
		<xs:sequence>
			<xs:element name="Condition" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="OrConditions" type="OrConditionsType" minOccurs="0"/>
			<xs:element name="AndConditions" type="AndConditionsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConditionType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Name"/>
			<xs:element ref="Values"/>
		</xs:choice>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="DataStructureObjectType"/>
					<xs:enumeration value="PCMObjectType"/>
					<xs:enumeration value="PropertyValue"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Name" type="xs:string"/>
	<xs:complexType name="OrConditionsType">
		<xs:sequence>
			<xs:element name="Condition" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="AndConditions" type="AndConditionsType" minOccurs="0"/>
			<xs:element name="OrConditions" type="OrConditionsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StructureType">
		<xs:choice>
			<xs:element name="Condition" type="ConditionType"/>
			<xs:element name="OrConditions" type="OrConditionsType"/>
			<xs:element name="AndConditions" type="AndConditionsType"/>
			<xs:element name="ChildObject" type="ChildObjectType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="COMMUNICATION"/>
					<xs:enumeration value="FUNCTIONAL"/>
					<xs:enumeration value="PCMSTRUCTURE"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Values" type="xs:string"/>
	<xs:complexType name="ChildObjectType">
		<xs:sequence>
			<xs:element name="ChildObject" type="ChildObjectType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SetPropertyValue" type="SetPropertyValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SetPropertyValueType">
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ListObjectType">
		<xs:attribute name="findMethod" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="ancestorDirectChild"/>
					<xs:enumeration value="ancestorSecondChild"/>
					<xs:enumeration value="ancestorPropertyValue"/>
					<xs:enumeration value="ancestorPropertyValueWithDefaults"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ancestorDsot" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="OPCServer"/>
					<xs:enumeration value="OPCClient"/>
					<xs:enumeration value="LN"/>
					<xs:enumeration value="GATEWAY"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="childObjectType" type="xs:string"/>
		<xs:attribute name="firstchildObjectType" type="xs:string"/>
		<xs:attribute name="secondchildObjectType" type="xs:string"/>
		<xs:attribute name="filterDsot" type="xs:string"/>
		<xs:attribute name="filterObjectType" type="xs:string"/>
		<xs:attribute name="propertyName" type="xs:string"/>
		<xs:attribute name="expectedDefaults" type="xs:string"/>
		<xs:attribute name="separators" type="xs:string"/>
		<xs:attribute name="selectorIndexes" type="xs:string"/>
		<xs:attribute name="idIndex" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/GooseControlBlock.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">GooseControlBlock</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDescription</Parameter>
		<Parameter name="Group">GOOSE</Parameter>
		<Parameter name="Type">REPORTCONTROL</Parameter>
		<Parameter name="IconFileName">GCB.ico</Parameter>
		<Parameter name="Tools">OnlineDiagnosticsRcbIec61850</Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="Visible">True</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">IEC61850 Proxy LLN0, IEC61850 LLN0, IEC61850SPA LLN0</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="sclXML">ReportControlBlockSCL</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="UpdateRCBSCL" category="[010] Basic">
			<Value>False</Value>
			<DescID>UpdateRCBSCLDesc</DescID>
			<CaptionID>UpdateRCBSCL</CaptionID>
			<Values type="boolean"/>
			<DataType>System.Boolean</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>UpdateRCBSCL</AttributeName>
		</Property>
		<Property name="ReportControlBlockSCL" category="[010] Basic">
			<Value/>
			<DescID>ReportControlBlockSCLDesc</DescID>
			<CaptionID>ReportControlBlockSCL</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>ReportControlBlockSCL</AttributeName>
		</Property>
		<Property name="GSESCL" category="[010] Basic">
			<Value/>
			<DescID>GSESCLDesc</DescID>
			<CaptionID>GSESCL</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>GSESCL</AttributeName>
		</Property>
		<Property name="datSet" category="[010] Basic">
			<Value/>
			<DescID>Dataset to be sent in GOOSE.</DescID>
			<CaptionID>datSet</CaptionID>
			<Values type="singleChoiceDynamic">
				<ListObjects findMethod="ancestorDirectChild" ancestorDsot="LN" filterDsot="DATASET"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>datSet</AttributeName>
		</Property>
		<!--Property name="rptID" category="[010] Basic">
			<Value></Value>
			<DescID>rptIDDesc</DescID>
			<CaptionID>rptID</CaptionID>
			<Values type="string"></Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>rptID</AttributeName>
		</Property-->
		<!--Property name="buffered" category="[010] Basic">
			<Value>True</Value>
			<DescID>bufferedDesc</DescID>
			<CaptionID>buffered</CaptionID>
			<Values type="boolean"/>
			<DataType>System.Boolean</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>buffered</AttributeName>
		</Property>
		<Property name="intgPd" category="[010] Basic">
			<Value>0</Value>
			<DescID>intgPdDesc</DescID>
			<CaptionID>intgPd</CaptionID>
			<Values type="numerical"/>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>intgPd</AttributeName>
		</Property-->
		<Property name="confRev" category="[010] Basic">
			<Value>1</Value>
			<DescID>confRevDesc</DescID>
			<CaptionID>confRev</CaptionID>
			<Values type="numerical"/>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>confRev</AttributeName>
		</Property>
		<!--Property name="bufTime" category="[010] Basic">
			<Value>100</Value>
			<DescID>bufTimDesc</DescID>
			<CaptionID>bufTim</CaptionID>
			<Values type="numerical"/>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>bufTime</AttributeName>
		</Property-->

		<Property name="MAC-Address" category="[080] Goose Address">
			<Value>01-0C-CD-01-00-00</Value>
			<DescID>MulticastAddressDesc</DescID>
			<CaptionID>MulticastAddress</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>WWW</Access>
			<AttributeName>MAC-Address</AttributeName>
		</Property>
		<!--Property name="APPID" category="[080] Goose Address">
			<Value>0</Value>
			<DescID>Application ID for the GOOSE control block.</DescID>
			<CaptionID>APPID</CaptionID>
			<Values type="numerical">
				<Min>0</Min>
				<Max>16383</Max>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>WWW</Access>
			<AttributeName>AppID</AttributeName>
		</Property-->
		<Property name="APPID" category="[080] Goose Address">
			<Value>0000</Value>
			<DescID>APPIDDesc</DescID>
			<CaptionID>APPID</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>WWW</Access>
			<AttributeName>AppID</AttributeName>
		</Property>

		<Property name="VLAN-PRIORITY" category="[080] Goose Address">
			<Value>4</Value>
			<DescID>VLAN-PriorityDesc</DescID>
			<CaptionID>VLAN-Priority</CaptionID>
			<Values type="numerical">
				<Min>0</Min>
				<Max>7</Max>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>WWW</Access>
			<AttributeName>VLAN-PRIORITY</AttributeName>
		</Property>
		<Property name="VLAN-ID" category="[080] Goose Address">
			<Value>000</Value>
			<DescID>VLAN-IDDesc</DescID>
			<CaptionID>VLAN-ID</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>WWW</Access>
			<AttributeName>VLAN-ID</AttributeName>
		</Property>
		<Property name="AppIDDescription" category="[080] Goose Address">
			<Value></Value>
			<DescID>GoIDDesc</DescID>
			<CaptionID>GoID</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>WWW</Access>
			<AttributeName>AppIDDescription</AttributeName>
		</Property>
		<Property name="MaxTime" category="[080] Goose Address">
			<Value>10000</Value>
			<DescID>MaxTimeDesc</DescID>
			<CaptionID>MaxTime</CaptionID>
			<Values type="numerical">
				<Min>0</Min>
				<Max>65535</Max>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>MaxTime</AttributeName>
		</Property>
		<Property name="MinTime" category="[080] Goose Address">
			<Value>2</Value>
			<DescID>MinTimeDesc</DescID>
			<CaptionID>MinTime</CaptionID>
			<Values type="numerical">
				<Min>0</Min>
				<Max>65535</Max>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>MinTime</AttributeName>
		</Property>
		<Property name="GSEType" category="[010] Basic">
			<Value>GOOSE</Value>
			<DescID>GSETypeDesc</DescID>
			<CaptionID>GSEType</CaptionID>
			<Values type="singleChoice">
				<Enum textID="GOOSE" value="GOOSE"/>
				<Enum textID="GSSE" value="GSSE"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName>GSEType</AttributeName>
		</Property>
	</Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/IEC61850 ENS.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectTypes>
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
  <Parameters type="InterfaceDefinition">
    <Parameter name="ObjectType">IEC61850 ENS</Parameter>
    <Parameter name="Caption">objectTypeCaption</Parameter>
    <Parameter name="Description">objectTypeDesc</Parameter>
    <Parameter name="Group">Data objects</Parameter>
    <Parameter name="Type">DO</Parameter>
    <Parameter name="IconFileName">ens.ico</Parameter>
    <Parameter name="Tools">OnlineDiagnosticsDataObject</Parameter>
    <Parameter name="DataServers" />
    <Parameter name="Verbs" />
    <Parameter name="Visible">False</Parameter>
    <Parameter name="CanInherit">False</Parameter>
    <Parameter name="ParentControlConditions">
      <Structure name="COMMUNICATION">
        <Condition type="DataStructureObjectType">LN</Condition>
      </Structure>
    </Parameter>
  </Parameters>
  <Parameters type="SCLExport">
    <Export name="sclXML">DOISCL</Export>
    <Export name="sAddr">MappedEvent, PrintBlock, Section</Export>
  </Parameters>
  <Properties type="PropertyDefinitions">
    <Property name="DOISCL" category="[010] Basic">
      <Value></Value>
      <DescID>DOSCLDesc</DescID>
      <CaptionID>DOISCL</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>HHH</Access>
      <AttributeName>DOISCL</AttributeName>
    </Property>
    <Property name="61850-Type" category="[010] Basic">
      <Value>ENS</Value>
      <DescID>61850-TypeDesc</DescID>
      <CaptionID>61850-Type</CaptionID>
      <Values type="singleChoice">
        <Enum textID="ACD" value="ACD" />
        <Enum textID="ACT" value="ACT" />
        <Enum textID="APC" value="APC" />
        <Enum textID="ASG" value="ASG" />
        <Enum textID="BCR" value="BCR" />
        <Enum textID="BSC" value="BSC" />
        <Enum textID="CMV" value="CMV" />
        <Enum textID="CSD" value="CSD" />
        <Enum textID="CURVE" value="CURVE" />
        <Enum textID="DEL" value="DEL" />
        <Enum textID="DPC" value="DPC" />
        <Enum textID="DPS" value="DPS" />
        <Enum textID="DPL" value="DPL" />
        <Enum textID="HDEL" value="HDEL" />
        <Enum textID="HMV" value="HMV" />
        <Enum textID="HWYE" value="HWYE" />
        <Enum textID="INC" value="INC" />
        <Enum textID="ING" value="ING" />
        <Enum textID="INS" value="INS" />
        <Enum textID="ISC" value="ISC" />
        <Enum textID="LPL" value="LPL" />
        <Enum textID="MV" value="MV" />
        <Enum textID="SAV" value="SAV" />
        <Enum textID="SEC" value="SEC" />
        <Enum textID="SEQ" value="SEQ" />
        <Enum textID="SPC" value="SPC" />
        <Enum textID="SPG" value="SPG" />
        <Enum textID="SPS" value="SPS" />
        <Enum textID="WYE" value="WYE" />
          <Enum textID="ENC" value="ENC" />
          <Enum textID="ENS" value="ENS" />
          <Enum textID="ENG" value="ENG" />
      </Values>
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RRR</Access>
      <AttributeName />
    </Property>
    <Property name="DOType" category="[010] Basic">
      <Value></Value>
      <DescID>DOTypeDesc</DescID>
      <CaptionID>DOType</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>HHH</Access>
      <AttributeName>DOType</AttributeName>
    </Property>
    <Property name="Section" category="[040] OPC Alarm and Event">
			<Value>0</Value>
			<DescID>SectionDesc</DescID>
			<CaptionID>Section</CaptionID>
			<Values type="numerical">
				<Min>0</Min>
				<Max>16</Max>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>HHW</Access>
			<AttributeName/>
		</Property>
		<Property name="PrintBlock" category="[040] OPC Alarm and Event">
			<Value>False</Value>
			<DescID>PrintBlockDesc</DescID>
			<CaptionID>PrintBlock</CaptionID>
			<Values type="boolean"/>
			<DataType>System.Boolean</DataType>
			<HelpKey/>
			<Access>HHW</Access>
			<AttributeName/>
		</Property>
		<Property name="MappedEvent" category="[040] OPC Alarm and Event">
			<Value/>
			<DescID>MappedEventDesc</DescID>
			<CaptionID>MappedEvent</CaptionID>
      <Values type="singleChoiceDynamic">
		<ListObjects findMethod="ancestorSecondChild" ancestorDsot="GATEWAY" firstchildObjectType="EventGroupDOEvents" secondchildObjectType="DiscreteEventGroup"/>
      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="IEC61850MeasurementScale" category="[050] Scale and Unit">
			<Value/>
			<DescID>IEC61850MeasurementScaleDesc</DescID>
			<CaptionID>IEC61850MeasurementScale</CaptionID>
			<Values type="singleChoiceDynamic">
				<ListObjects findMethod="ancestorDirectChild" ancestorDsot="GATEWAY" childObjectType="ScaleGroup"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
  </Properties>
</ObjectType>

</ObjectTypes>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/SimpleEventCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Markku Hamarila/RSC (ABB OY Substation Automation) -->
<ObjectTypes>
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">SimpleEventProcess 4.0</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Event Classes</Parameter>
		<Parameter name="Type">EVENT</Parameter>
		<Parameter name="IconFileName">ae.ico</Parameter>
		<Parameter name="Tools"/>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">True</Parameter>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">SimpleEventGroup</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="CDATA">BaseType, VarType</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="OPCObjectType" category="[010] Basic">
			<Value>Event Category</Value>
			<DescID>OPCObjectTypeDesc</DescID>
			<CaptionID>OPCObjectType</CaptionID>
			<Values type="string">
      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHR</Access>
			<AttributeName>OPCObjectType</AttributeName>
		</Property>
		<Property name="BaseType" category="Basic">
			<Value>SimpleEventProcess</Value>
			<DescID>Base Type of Event Condition</DescID>
			<CaptionID>Base Type</CaptionID>
			<Values type="singleChoice">
				<Enum textID="Condition Process" value="ConditionProcess"/>
				<Enum textID="Simple Event Process" value="SimpleEventProcess"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName/>
		</Property>
		<Property name="VarType" category="Basic">
			<Value>3</Value>
			<DescID>Event Class Type that can be assigned with this event category</DescID>
			<CaptionID>Event Class Type</CaptionID>
			<Values type="singleChoice">
				<Enum textID="Discrete" value="3"/>
				<Enum textID="Level" value="4"/>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>HWW</Access>
			<AttributeName/>
		</Property>
	</Properties>
</ObjectType>
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">SimpleEventProcess</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Event Classes</Parameter>
		<Parameter name="Type">EVENT</Parameter>
		<Parameter name="IconFileName">ae.ico</Parameter>
		<Parameter name="Tools"/>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">False</Parameter>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">SimpleEventGroup</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="CDATA">BaseType, VarType</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="OPCObjectType" category="[010] Basic">
			<Value>Event Category</Value>
			<DescID>OPCObjectTypeDesc</DescID>
			<CaptionID>OPCObjectType</CaptionID>
			<Values type="string">
      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHR</Access>
			<AttributeName>OPCObjectType</AttributeName>
		</Property>
		<Property name="BaseType" category="Basic">
			<Value>SimpleEventProcess</Value>
			<DescID>Base Type of Event Condition</DescID>
			<CaptionID>Base Type</CaptionID>
			<Values type="singleChoice">
				<Enum textID="Condition Process" value="ConditionProcess"/>
				<Enum textID="Simple Event Process" value="SimpleEventProcess"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName/>
		</Property>
		<Property name="VarType" category="Basic">
			<Value>3</Value>
			<DescID>Event Class Type that can be assigned with this event category</DescID>
			<CaptionID>Event Class Type</CaptionID>
			<Values type="singleChoice">
				<Enum textID="Discrete" value="3"/>
				<Enum textID="Level" value="4"/>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>HHW</Access>
			<AttributeName/>
		</Property>
	</Properties>
</ObjectType>
</ObjectTypes>
