=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/ObjectType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by XMLSPY 2006 Professional Ed., Installed for 5 users (ABB Oy) -->
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Markku Hamarila/RSC (ABB OY Substation Automation) -->
<!--W3C Schema generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Access" type="xs:string"/>
	<xs:element name="AttributeName" type="xs:string"/>
	<xs:element name="HelpKey" type="xs:string"/>
	<xs:element name="CaptionID" type="xs:string"/>
	<xs:element name="ConfigurationProperties" type="xs:string"/>
	<xs:element name="DataType" type="xs:string"/>
	<xs:element name="DescID" type="xs:string"/>
	<xs:complexType name="EnumType">
		<xs:attribute name="textID" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ExportType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="ConfigurationProperties" minOccurs="0"/>
			<xs:element name="List" type="ListType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="exportType" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ListType">
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="properties" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Max" type="xs:integer"/>
	<xs:element name="Min" type="xs:integer"/>
	<xs:element name="ObjectTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ObjectType" type="tObjectType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ObjectType" type="tObjectType"/>
	<xs:complexType name="tObjectType">
		<xs:sequence>
			<xs:element name="Parameters" type="ParametersType" maxOccurs="unbounded"/>
			<xs:element name="Properties" type="PropertiesType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ParameterType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="List" type="ListType" maxOccurs="unbounded"/>
			<xs:element name="Structure" type="StructureType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ParametersType">
		<xs:choice>
			<xs:element name="Parameter" type="ParameterType" maxOccurs="unbounded"/>
			<xs:element name="Export" type="ExportType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PrivateType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PropertiesType">
		<xs:sequence>
			<xs:element name="Property" type="PropertyType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PropertyType">
		<xs:sequence>
			<xs:element ref="Value"/>
			<xs:element ref="DescID"/>
			<xs:element ref="CaptionID"/>
			<xs:element name="Values" type="ValuesType"/>
			<xs:element ref="DataType"/>
			<xs:element ref="HelpKey"/>
			<xs:element ref="Access"/>
			<xs:element ref="AttributeName" minOccurs="0"/>
			<xs:element name="Private" type="PrivateType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="category" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Value" type="xs:string"/>
	<xs:complexType name="ValuesType">
		<xs:sequence>
			<xs:element name="Enum" type="EnumType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="Min" minOccurs="0"/>
			<xs:element ref="Max" minOccurs="0"/>
			<xs:element name="ListObjects" type="ListObjectType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="numerical"/>
					<xs:enumeration value="singleChoice"/>
					<xs:enumeration value="singleChoiceDynamic"/>
					<xs:enumeration value="singleChoiceEditable"/>
					<xs:enumeration value="multiChoice"/>
					<xs:enumeration value="string"/>
					<xs:enumeration value="password"/>
					<xs:enumeration value="boolean"/>
					<xs:enumeration value="SoftPLCOPCItemPath"/>					
					<xs:enumeration value="DocumentLibraryReference"/>		
					<xs:enumeration value="IPOrHostname" />
					<xs:enumeration value="IPOrHostnameWithPort" />								
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="AndConditionsType">
		<xs:sequence>
			<xs:element name="Condition" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="OrConditions" type="OrConditionsType" minOccurs="0"/>
			<xs:element name="AndConditions" type="AndConditionsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConditionType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Name"/>
			<xs:element ref="Values"/>
		</xs:choice>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="DataStructureObjectType"/>
					<xs:enumeration value="PCMObjectType"/>
					<xs:enumeration value="PropertyValue"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Name" type="xs:string"/>
	<xs:complexType name="OrConditionsType">
		<xs:sequence>
			<xs:element name="Condition" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="AndConditions" type="AndConditionsType" minOccurs="0"/>
			<xs:element name="OrConditions" type="OrConditionsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StructureType">
		<xs:choice>
			<xs:element name="Condition" type="ConditionType"/>
			<xs:element name="OrConditions" type="OrConditionsType"/>
			<xs:element name="AndConditions" type="AndConditionsType"/>
			<xs:element name="ChildObject" type="ChildObjectType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="COMMUNICATION"/>
					<xs:enumeration value="FUNCTIONAL"/>
					<xs:enumeration value="PCMSTRUCTURE"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Values" type="xs:string"/>
	<xs:complexType name="ChildObjectType">
		<xs:sequence>
			<xs:element name="ChildObject" type="ChildObjectType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SetPropertyValue" type="SetPropertyValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SetPropertyValueType">
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ListObjectType">
		<xs:attribute name="findMethod" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="ancestorDirectChild"/>
					<xs:enumeration value="ancestorSecondChild"/>
					<xs:enumeration value="ancestorPropertyValue"/>
					<xs:enumeration value="ancestorPropertyValueWithDefaults"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ancestorDsot" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="OPCServer"/>
					<xs:enumeration value="OPCClient"/>
					<xs:enumeration value="LN"/>
					<xs:enumeration value="GATEWAY"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="childObjectType" type="xs:string"/>
		<xs:attribute name="firstchildObjectType" type="xs:string"/>
		<xs:attribute name="secondchildObjectType" type="xs:string"/>
		<xs:attribute name="filterDsot" type="xs:string"/>
		<xs:attribute name="filterObjectType" type="xs:string"/>
		<xs:attribute name="propertyName" type="xs:string"/>
		<xs:attribute name="expectedDefaults" type="xs:string"/>
		<xs:attribute name="separators" type="xs:string"/>
		<xs:attribute name="selectorIndexes" type="xs:string"/>
		<xs:attribute name="idIndex" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/Generic Logical Device.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">LD</Parameter>
		<Parameter name="Caption">Logical Device</Parameter>
		<Parameter name="Description">Logical Device</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">LD</Parameter>
		<Parameter name="IconFileName">ld.ico</Parameter>
		<Parameter name="Tools"/>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="CanInherit">True</Parameter>
	    <Parameter name="Visible">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="DataStructureObjectType">IED, LSG</Condition>
			</Structure>
		</Parameter>
	</Parameters>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/DiscreteDirectEventClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Markku Hamarila/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">DirectValue</Parameter>
		<Parameter name="Caption">objectTypeCaptionDiscreteDirect</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Event Classes</Parameter>
		<Parameter name="Type">EVENT</Parameter>
		<Parameter name="IconFileName">ae.ico</Parameter>
		<Parameter name="Tools"/>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">True</Parameter>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">DiscreteEventGroup</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="CDATA">BaseType, Message, Severity, SimpleEventCategory</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
			<Property name="OPCObjectType" category="[010] Basic">
			<Value>Event Class</Value>
			<DescID>OPCObjectTypeDesc</DescID>
			<CaptionID>OPCObjectType</CaptionID>
			<Values type="string">
      </Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHR</Access>
			<AttributeName>OPCObjectType</AttributeName>
		</Property>
	<Property name="BaseType" category="Basic">
			<Value>DirectValue</Value>
			<DescID>Base Type of Command Tracking Condition</DescID>
			<CaptionID>Base Type</CaptionID>
			<Values type="singleChoice">
				<Enum textID="Direct Value" value="DirectValue"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName/>
		</Property>
		<Property name="Severity" category="Basic">
			<Value>4</Value>
			<DescID>Severity</DescID>
			<CaptionID>Severity</CaptionID>
			<Values type="numerical">
				<Min>1</Min>
				<Max>1000</Max>
			</Values>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="Message" category="Basic">
			<Value>Message</Value>
			<DescID>Message</DescID>
			<CaptionID>Message</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
		<Property name="SimpleEventCategory" category="Basic">
			<Value/>
			<DescID>Simple Event Category to use</DescID>
			<CaptionID>Simple Event Category</CaptionID>
			<Values type="singleChoiceDynamic">
				<ListObjects findMethod="ancestorSecondChild" ancestorDsot="GATEWAY" firstchildObjectType="EventGroupCommonDefinitions" secondchildObjectType="SimpleEventGroup"/>
			</Values>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName/>
		</Property>
	</Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/ReportClient.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
  <Parameters type="InterfaceDefinition">
    <Parameter name="ObjectType">ReportClient</Parameter>
    <Parameter name="Caption">objectTypeCaption</Parameter>
    <Parameter name="Description">objectTypeDesc</Parameter>
    <Parameter name="Group">Communication</Parameter>
    <Parameter name="Type">REPORTCLIENT</Parameter>
    <Parameter name="IconFileName">ReportClient.ico</Parameter>
    <Parameter name="Tools">
    </Parameter>
    <Parameter name="DataServers" />
    <Parameter name="Verbs" />
    <Parameter name="CanInherit">False</Parameter>
    <Parameter name="ParentControlConditions">
      <Structure name="COMMUNICATION">
        <Condition type="DataStructureObjectType">REPORTENABLED</Condition>
      </Structure>
    </Parameter>
  </Parameters>
  <Properties type="PropertyDefinitions">
    <Property name="iedName" category="[010] Basic">
      <Value>Report Client</Value>
      <DescID>iedNameDesc</DescID>
      <CaptionID>iedName</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName>iedName</AttributeName>
    </Property>
    <Property name="ldInst" category="[010] Basic">
      <Value>LD1</Value>
      <DescID>ldInstDesc</DescID>
      <CaptionID>ldInst</CaptionID>
      <Values type="string">
      </Values>
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName>ldInst</AttributeName>
    </Property>
    <Property name="lnInst" category="[010] Basic">
      <Value></Value>
      <DescID>lnInstDesc</DescID>
      <CaptionID>lnInst</CaptionID>
      <Values type="string">
      </Values>
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName>lnInst</AttributeName>
    </Property>
    <Property name="prefix" category="[010] Basic">
      <Value></Value>
      <DescID>prefixDesc</DescID>
      <CaptionID>prefix</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName>prefix</AttributeName>
    </Property>
    <Property name="lnClass" category="[010] Basic">
      <Value>LLN0</Value>
      <DescID>lnClassDesc</DescID>
      <CaptionID>lnClass</CaptionID>
      <Values type="string" />
      <DataType>System.String</DataType>
      <HelpKey />
      <Access>RWW</Access>
      <AttributeName>lnClass</AttributeName>
    </Property>
  </Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/EventQueueGroup.xml
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">EventQueueEventGroup</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">GENERIC</Parameter>
		<Parameter name="IconFileName">scale.ico</Parameter>
		<Parameter name="Tools">SortChildNsoVerb</Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">False</Parameter> 
		<Parameter name="CanInherit">False</Parameter> 
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">EventGroupClientEvents</Condition>
			</Structure>
		</Parameter>
	</Parameters>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/Generic IED.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">IED</Parameter>
		<Parameter name="Caption">Generic IED</Parameter>
		<Parameter name="Description">IED</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">IED</Parameter>
		<Parameter name="IconFileName">genIED.ico</Parameter>
		<Parameter name="Tools"></Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="DataStructureObjectType">SUBNETWORK</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="SCLIedType" category="">
			<Value>Generic IED</Value>
			<DescID>SCLIedTypeDesc</DescID>
			<CaptionID>SCLIedType</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName>SCLIedType</AttributeName>
		</Property>
		<Property name="SCLManufacturer" category="">
			<Value/>
			<DescID>SCLManufacturerDesc</DescID>
			<CaptionID>SCLManufacturer</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName>SCLManufacturer</AttributeName>
		</Property>
		<Property name="SCLPCMObjectTypeName" category="">
			<Value/>
			<DescID>SCLPCMObjectTypeName</DescID>
			<CaptionID>SCLPCMObjectTypeName</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>SCLPCMObjectTypeName</AttributeName>
		</Property>
		<Property name="SCLConfigVersion" category="">
			<Value/>
			<DescID>SCLConfigVersionDesc</DescID>
			<CaptionID>SCLConfigVersion</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>RRR</Access>
			<AttributeName>configVersion</AttributeName>
		</Property>
	</Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/ReportEnabled.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">ReportEnabled</Parameter>
		<Parameter name="Caption">objectTypeCaption</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">REPORTENABLED</Parameter>
		<Parameter name="IconFileName">ReportEnabled.ico</Parameter>
		<Parameter name="Tools"></Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
			        <Condition type="PCMObjectType">ReportControlBlock, ReportControlBlock 3.4</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="max" category="[010] Report Enabled">
			<Value>1</Value>
			<DescID>maxDesc</DescID>
			<CaptionID>max</CaptionID>
			<Values type="numerical"/>
			<DataType>System.Int32</DataType>
			<HelpKey/>
			<Access>RWW</Access>
			<AttributeName>max</AttributeName>
		</Property>
	</Properties>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/BinStepPosGroup.xml
<ObjectType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">BINSTEPPOSEventGroup</Parameter>
		<Parameter name="Caption">BINSTEPPOS Event Group</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">GENERIC</Parameter>
		<Parameter name="IconFileName">scale.ico</Parameter>
		<Parameter name="Tools">SortChildNsoVerb</Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="Visible">False</Parameter>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">EventGroupDOEvents</Condition>
			</Structure>
		</Parameter>
	</Parameters>
</ObjectType>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/object types/xml/DataSet.xml
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Mikko Ripatti/RSC (ABB OY Substation Automation) -->
<ObjectTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectType.xsd">	
<ObjectType >
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">DataSet 3.5</Parameter>
		<Parameter name="Caption">Data Set</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">DATASET</Parameter>
		<Parameter name="IconFileName">ds.ico</Parameter>
		<Parameter name="Tools">DatasetEdit</Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">IEC61850 LLN0, IEC61850 LN, IEC61850GW LD0 LLN0, SSS LLN0, IEC61850 Proxy LLN0, IEC61850 Proxy LN</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="sclXML">DataSetSCL</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="DataSetSCL" category="[010] Basic">
			<Value>&lt;DataSet name="Data Set" xmlns="http://www.iec.ch/61850/2003/SCL" /&gt;</Value>
			<DescID>DataSetSCLDesc</DescID>
			<CaptionID>DataSetSCL</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>LNClass</AttributeName>
		</Property>
	</Properties>
</ObjectType>
<ObjectType >
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">DataSet 3.4</Parameter>
		<Parameter name="Caption">Data Set</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">DATASET</Parameter>
		<Parameter name="IconFileName">ds.ico</Parameter>
		<Parameter name="Tools">DatasetEdit</Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">IEC61850 LLN0, IEC61850 LN, IEC61850GW LD0 LLN0, SSS LLN0</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="sclXML">DataSetSCL</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="DataSetSCL" category="[010] Basic">
			<Value>&lt;DataSet name="Data Set" xmlns="http://www.iec.ch/61850/2003/SCL" /&gt;</Value>
			<DescID>DataSetSCLDesc</DescID>
			<CaptionID>DataSetSCL</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>LNClass</AttributeName>
		</Property>
	</Properties>
</ObjectType>
<ObjectType>
	<Parameters type="InterfaceDefinition">
		<Parameter name="ObjectType">DataSet</Parameter>
		<Parameter name="Caption">Data Set</Parameter>
		<Parameter name="Description">objectTypeDesc</Parameter>
		<Parameter name="Group">Communication</Parameter>
		<Parameter name="Type">DATASET</Parameter>
		<Parameter name="IconFileName">ds.ico</Parameter>
		<Parameter name="Tools">DatasetEdit</Parameter>
		<Parameter name="DataServers"/>
		<Parameter name="Verbs"/>
		<Parameter name="CanInherit">False</Parameter>
		<Parameter name="ParentControlConditions">
			<Structure name="COMMUNICATION">
				<Condition type="PCMObjectType">IEC61850 LLN0, IEC61850 LN, IEC61850GW LD0 LLN0</Condition>
			</Structure>
		</Parameter>
	</Parameters>
	<Parameters type="SCLExport">
		<Export name="sclXML">DataSetSCL</Export>
	</Parameters>
	<Properties type="PropertyDefinitions">
		<Property name="DataSetSCL" category="[010] Basic">
			<Value>&lt;DataSet name="Data Set" xmlns="http://www.iec.ch/61850/2003/SCL" /&gt;</Value>
			<DescID>DataSetSCLDesc</DescID>
			<CaptionID>DataSetSCL</CaptionID>
			<Values type="string"/>
			<DataType>System.String</DataType>
			<HelpKey/>
			<Access>HHH</Access>
			<AttributeName>LNClass</AttributeName>
		</Property>
	</Properties>
</ObjectType>
</ObjectTypes>
