=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/ConnPack.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema targetNamespace="abb.pcm.objectTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pcm="abb.pcm.objectTypes" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="InCompatibleConnPacks">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="InCompatibleConnPack">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="version" type="xs:decimal" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PGSEnergy/ORION_SCADA/prog/61850_OPC_Server/CET/bin/ConnPack.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<InCompatibleConnPacks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="abb.pcm.objectTypes connpack.xsd" xmlns:pcm="abb.pcm.objectTypes" version="1.1">
  <InCompatibleConnPack name="SPA" version="0.0-9.9" />
  <InCompatibleConnPack name="LON" version="0.0-9.9" />
  <InCompatibleConnPack name="IEC61850" version="0.0-9.9" />
  <InCompatibleConnPack name="REx670" version="0.0-9.9" />  
  <InCompatibleConnPack name="REx 670" version="0.0-9.9" />    
  <InCompatibleConnPack name="REx 630" version="0.0-9.9" />    
  <InCompatibleConnPack name="REx 650" version="0.0-9.9" />  
  <InCompatibleConnPack name="REF 630" version="0.0-9.9" />  
  <InCompatibleConnPack name="REM 630" version="0.0-9.9" />  
  <InCompatibleConnPack name="RET 630" version="0.0-9.9" />  
  <InCompatibleConnPack name="RBX 615" version="0.0-9.9" />    
  <InCompatibleConnPack name="GenericIEC61850IED" version="0.0-9.9" />  
	<InCompatibleConnPack name="RED615" version="0.0-9.9" />  
	<InCompatibleConnPack name="REF541_3_5" version="0.0-9.9" />  
	<InCompatibleConnPack name="REF542Plus" version="0.0-9.9" />  
	<InCompatibleConnPack name="REF615" version="0.0-9.9" />  
	<InCompatibleConnPack name="REF615A" version="0.0-9.9" />  
	<InCompatibleConnPack name="REM543_5" version="0.0-9.9" />  
	<InCompatibleConnPack name="REM615" version="0.0-9.9" />  
	<InCompatibleConnPack name="REM615A" version="0.0-9.9" />  
	<InCompatibleConnPack name="RER620A" version="0.0-9.9" />  
	<InCompatibleConnPack name="RET541_3_5" version="0.0-9.9" />  
	<InCompatibleConnPack name="RET615" version="0.0-9.9" />  
	<InCompatibleConnPack name="RET615A" version="0.0-9.9" />  
	<InCompatibleConnPack name="REU615" version="0.0-9.9" />  
	<InCompatibleConnPack name="REX521" version="0.0-9.9" />  
	<InCompatibleConnPack name="SPACOM" version="0.0-9.9" />
	<InCompatibleConnPack name="REF620" version="0.0-9.9" />
	<InCompatibleConnPack name="REM620" version="0.0-9.9" />
	<InCompatibleConnPack name="RET620" version="0.0-9.9" />
	<InCompatibleConnPack name="REF620A" version="0.0-9.9" />
	<InCompatibleConnPack name="REM620A" version="0.0-9.9" />
	<InCompatibleConnPack name="RET620A" version="0.0-9.9" />
</InCompatibleConnPacks>
